server:
  port: 31001
  servlet:
    context-path: /
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_cms

security:
  basic:
    enabled: false