server:
  port: 31001
  servlet:
    context-path: /
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_cms

security:
  basic:
    enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:60010/eureka/,http://localhost:60011/eureka/
  instance:
    prefer-ip-address: true