server:
  port: ${port:60010}
spring:
  application:
    name: xc-goven-center
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_server:http://localhost:60010/eureka}
  instance:
    hostname: ${eureka_domain:peer1}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000


